### ISSUE TITLE
Error in load from fileURLToPath when running on Windows 11

### ISSUE THREAD

**Issue by jemmyw** [cyyynthia/vite-plugin-magical-svg#11]
I have run into an issue when trying to run a build on Windows. The error is 'The URL must be of scheme file' and it is coming from this line:

https://github.com/cyyynthia/vite-plugin-magical-svg/blob/79698281b82acae7c14b93aec97b585feb376a0b/src/index.ts#L189

It seems that `new URL(id, 'file://')` does not work as expected when the id is given in the usual Windowsy way of `c:\\path\\to\\file` and the schema is set to `c:` or something, no matter what you do (this is with Node 20).

I've temporarily fixed it locally by changing the line in the bundled code in node_modules to:

```
const filePath = (0, url_1.fileURLToPath)(`file:///${id}`);
```

and then it works fine. So the underlying problem is in how URL works with Windows paths, and it can be worked around.

p.s. great package btw, it works really well, many thanks!

**Comment by cyyynthia** [comment]
Thanks for reporting (and the positive feedback!)

This should be fixed in 1.2.2 👍🏻
