### ISSUE TITLE
`width` and `height` on `<svg>` not preserved

### ISSUE THREAD

**Issue by jgarplind** [cyyynthia/vite-plugin-magical-svg#13]
I'm using svgr today, and there I can do this:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="1em" height="1em">` (I found an old article saying that controlling svg size via `font-size` this way was convenient, and have used it since).

Anyway, using this plugin it appears that the `width` and `height` are erased, leading to a huge visual difference (literally, the `<svg>`s become huge, due to large base size somehow I guess? I'm no SVG expert).

Other than that, at a first glance this is a nice plug-and-play replacement for svgr!

**Comment by cyyynthia** [comment]
This, along with a bunch of new features will be released ~tomorrow!
- The screenshot doesn't show it but the generated code does have the width and height set
- The plugin is now able to "restore" missing viewboxes based on width and height
- The plugin is also able to replace existing fill and stroke with `currentColor` to allow controlling the color via css color.

![screenshot](https://github.com/user-attachments/assets/fe9b7a7e-ef35-4119-b7b0-f3edc23ecda8)
